train_dataset: '/content/drive/MyDrive/MedViLL-runimage/data/dataset/openi/Train.jsonl'
valid_dataset: ''
test_dataset: ''
epochs: 1
batch_size: 32
num_workers: 2
img_encoder: 'ViT'
img_size: 224
img_embed_pool_type: 'max'
num_image_embeds: 196
img_channel: 3
image_res: 224
vision_width: 768
embedding_size: 768
hidden_size: 768
temp: 0.07
lr: 2e-5  # Không có dấu nháy
gradient_accumulation_steps: 4
warmup: 0.1
warmup_steps: 0
tokenizer: "bert-base-uncased"
bert_model: "bert-base-uncased"
vocab_size: 30522
beta1: 0.9
beta2: 0.999
eps: 1e-6
weight_decay: 0.01
seq_len: 32
max_seq_len: 512